package com.ariix.twInvoice;

public class PromotionType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTION_TYPE.ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTION_TYPE.NAME
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTION_TYPE.DESCRIPTION
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTION_TYPE.ID
	 * @return  the value of PROMOTION_TYPE.ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTION_TYPE.ID
	 * @param id  the value for PROMOTION_TYPE.ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTION_TYPE.NAME
	 * @return  the value of PROMOTION_TYPE.NAME
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTION_TYPE.NAME
	 * @param name  the value for PROMOTION_TYPE.NAME
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTION_TYPE.DESCRIPTION
	 * @return  the value of PROMOTION_TYPE.DESCRIPTION
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTION_TYPE.DESCRIPTION
	 * @param description  the value for PROMOTION_TYPE.DESCRIPTION
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}