package com.ariix.twInvoice;

import com.ariix.twInvoice.PromotionsRules;

public interface PromotionsRulesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROMOTIONS_RULES
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROMOTIONS_RULES
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	int insert(PromotionsRules record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROMOTIONS_RULES
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	int insertSelective(PromotionsRules record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROMOTIONS_RULES
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	PromotionsRules selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROMOTIONS_RULES
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	int updateByPrimaryKeySelective(PromotionsRules record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROMOTIONS_RULES
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	int updateByPrimaryKey(PromotionsRules record);
}