package com.ariix.twInvoice;

import java.util.Date;

public class Promotions {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS.ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS.NAME
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS.START_DATE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS.END_DATE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS.PROMOTION_MSG_KEY
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private String promotionMsgKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS.WAREHOUSE_ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private Long warehouseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS.COUNTRY_CODE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private String countryCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS.CREATE_DATE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS.ID
	 * @return  the value of PROMOTIONS.ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS.ID
	 * @param id  the value for PROMOTIONS.ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS.NAME
	 * @return  the value of PROMOTIONS.NAME
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS.NAME
	 * @param name  the value for PROMOTIONS.NAME
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS.START_DATE
	 * @return  the value of PROMOTIONS.START_DATE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS.START_DATE
	 * @param startDate  the value for PROMOTIONS.START_DATE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS.END_DATE
	 * @return  the value of PROMOTIONS.END_DATE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS.END_DATE
	 * @param endDate  the value for PROMOTIONS.END_DATE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS.PROMOTION_MSG_KEY
	 * @return  the value of PROMOTIONS.PROMOTION_MSG_KEY
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public String getPromotionMsgKey() {
		return promotionMsgKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS.PROMOTION_MSG_KEY
	 * @param promotionMsgKey  the value for PROMOTIONS.PROMOTION_MSG_KEY
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setPromotionMsgKey(String promotionMsgKey) {
		this.promotionMsgKey = promotionMsgKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS.WAREHOUSE_ID
	 * @return  the value of PROMOTIONS.WAREHOUSE_ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public Long getWarehouseId() {
		return warehouseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS.WAREHOUSE_ID
	 * @param warehouseId  the value for PROMOTIONS.WAREHOUSE_ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setWarehouseId(Long warehouseId) {
		this.warehouseId = warehouseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS.COUNTRY_CODE
	 * @return  the value of PROMOTIONS.COUNTRY_CODE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public String getCountryCode() {
		return countryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS.COUNTRY_CODE
	 * @param countryCode  the value for PROMOTIONS.COUNTRY_CODE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS.CREATE_DATE
	 * @return  the value of PROMOTIONS.CREATE_DATE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS.CREATE_DATE
	 * @param createDate  the value for PROMOTIONS.CREATE_DATE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}