package com.ariix.twInvoice;

import java.math.BigDecimal;
import java.util.Date;

public class PromotionsRules {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS_RULES.ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS_RULES.PROMOTIONS_ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private Long promotionsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS_RULES.PROMOTION_TYPE_ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private Long promotionTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS_RULES.FROM_PV
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private BigDecimal fromPv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS_RULES.TO_PV
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private BigDecimal toPv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS_RULES.FROM_AMOUNT
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private BigDecimal fromAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS_RULES.TO_AMOUNT
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private BigDecimal toAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS_RULES.DISCOUNT_AMOUNT
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private BigDecimal discountAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS_RULES.DISCOUNT_PENCENAGE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private BigDecimal discountPencenage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS_RULES.GIVE_ITEMS
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private String giveItems;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS_RULES.INCLUDE_PRODUCTS
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private String includeProducts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS_RULES.EXCLUDE_PRODUCTS
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private String excludeProducts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROMOTIONS_RULES.CREATE_DATE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS_RULES.ID
	 * @return  the value of PROMOTIONS_RULES.ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS_RULES.ID
	 * @param id  the value for PROMOTIONS_RULES.ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS_RULES.PROMOTIONS_ID
	 * @return  the value of PROMOTIONS_RULES.PROMOTIONS_ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public Long getPromotionsId() {
		return promotionsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS_RULES.PROMOTIONS_ID
	 * @param promotionsId  the value for PROMOTIONS_RULES.PROMOTIONS_ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setPromotionsId(Long promotionsId) {
		this.promotionsId = promotionsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS_RULES.PROMOTION_TYPE_ID
	 * @return  the value of PROMOTIONS_RULES.PROMOTION_TYPE_ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public Long getPromotionTypeId() {
		return promotionTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS_RULES.PROMOTION_TYPE_ID
	 * @param promotionTypeId  the value for PROMOTIONS_RULES.PROMOTION_TYPE_ID
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setPromotionTypeId(Long promotionTypeId) {
		this.promotionTypeId = promotionTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS_RULES.FROM_PV
	 * @return  the value of PROMOTIONS_RULES.FROM_PV
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public BigDecimal getFromPv() {
		return fromPv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS_RULES.FROM_PV
	 * @param fromPv  the value for PROMOTIONS_RULES.FROM_PV
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setFromPv(BigDecimal fromPv) {
		this.fromPv = fromPv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS_RULES.TO_PV
	 * @return  the value of PROMOTIONS_RULES.TO_PV
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public BigDecimal getToPv() {
		return toPv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS_RULES.TO_PV
	 * @param toPv  the value for PROMOTIONS_RULES.TO_PV
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setToPv(BigDecimal toPv) {
		this.toPv = toPv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS_RULES.FROM_AMOUNT
	 * @return  the value of PROMOTIONS_RULES.FROM_AMOUNT
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public BigDecimal getFromAmount() {
		return fromAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS_RULES.FROM_AMOUNT
	 * @param fromAmount  the value for PROMOTIONS_RULES.FROM_AMOUNT
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setFromAmount(BigDecimal fromAmount) {
		this.fromAmount = fromAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS_RULES.TO_AMOUNT
	 * @return  the value of PROMOTIONS_RULES.TO_AMOUNT
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public BigDecimal getToAmount() {
		return toAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS_RULES.TO_AMOUNT
	 * @param toAmount  the value for PROMOTIONS_RULES.TO_AMOUNT
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setToAmount(BigDecimal toAmount) {
		this.toAmount = toAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS_RULES.DISCOUNT_AMOUNT
	 * @return  the value of PROMOTIONS_RULES.DISCOUNT_AMOUNT
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public BigDecimal getDiscountAmount() {
		return discountAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS_RULES.DISCOUNT_AMOUNT
	 * @param discountAmount  the value for PROMOTIONS_RULES.DISCOUNT_AMOUNT
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS_RULES.DISCOUNT_PENCENAGE
	 * @return  the value of PROMOTIONS_RULES.DISCOUNT_PENCENAGE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public BigDecimal getDiscountPencenage() {
		return discountPencenage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS_RULES.DISCOUNT_PENCENAGE
	 * @param discountPencenage  the value for PROMOTIONS_RULES.DISCOUNT_PENCENAGE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setDiscountPencenage(BigDecimal discountPencenage) {
		this.discountPencenage = discountPencenage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS_RULES.GIVE_ITEMS
	 * @return  the value of PROMOTIONS_RULES.GIVE_ITEMS
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public String getGiveItems() {
		return giveItems;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS_RULES.GIVE_ITEMS
	 * @param giveItems  the value for PROMOTIONS_RULES.GIVE_ITEMS
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setGiveItems(String giveItems) {
		this.giveItems = giveItems;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS_RULES.INCLUDE_PRODUCTS
	 * @return  the value of PROMOTIONS_RULES.INCLUDE_PRODUCTS
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public String getIncludeProducts() {
		return includeProducts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS_RULES.INCLUDE_PRODUCTS
	 * @param includeProducts  the value for PROMOTIONS_RULES.INCLUDE_PRODUCTS
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setIncludeProducts(String includeProducts) {
		this.includeProducts = includeProducts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS_RULES.EXCLUDE_PRODUCTS
	 * @return  the value of PROMOTIONS_RULES.EXCLUDE_PRODUCTS
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public String getExcludeProducts() {
		return excludeProducts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS_RULES.EXCLUDE_PRODUCTS
	 * @param excludeProducts  the value for PROMOTIONS_RULES.EXCLUDE_PRODUCTS
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setExcludeProducts(String excludeProducts) {
		this.excludeProducts = excludeProducts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROMOTIONS_RULES.CREATE_DATE
	 * @return  the value of PROMOTIONS_RULES.CREATE_DATE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROMOTIONS_RULES.CREATE_DATE
	 * @param createDate  the value for PROMOTIONS_RULES.CREATE_DATE
	 * @mbggenerated  Mon Jan 22 16:22:52 CST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}